# Generated by Django 3.0.7 on 2020-06-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardee', models.CharField(max_length=64)),
                ('award', models.CharField(max_length=64)),
                ('awarding_body', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('url', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('REG', 'publication'), ('SPP', 'conference paper')], max_length=3)),
                ('authors', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('journal', models.CharField(max_length=256)),
                ('volume', models.IntegerField(blank=True)),
                ('issue', models.IntegerField(blank=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('start_page', models.IntegerField(blank=True)),
                ('end_page', models.IntegerField(blank=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('subgroup', models.CharField(choices=[('ITO', 'IPL Team One'), ('VIP', 'Video and Image Processing'), ('CXT', 'Complex Systems Team'), ('SBO', 'SyncBioOptics'), ('CSG', 'Complexity Science Group')], max_length=3)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
