# Generated by Django 3.0.7 on 2020-06-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('awardee', models.CharField(max_length=255)),
                ('award', models.CharField(max_length=255)),
                ('awarding_body', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('url', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(choices=[('ITO', 'IPL Team One'), ('VIP', 'Video and Image Processing'), ('CXT', 'Complex Systems Team'), ('SBO', 'SyncBioOptics'), ('CSG', 'Complexity Science Group')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('publication_type', models.CharField(choices=[('reg', 'publication'), ('spp', 'conference paper')], max_length=3)),
                ('authors', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('journal', models.CharField(max_length=256)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('year', models.IntegerField()),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('subgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Subgroup', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('source', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subgroup', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('faculty', 'Faculty'), ('graduate', 'Graduate student'), ('undergraduate', 'Undergraduate student'), ('alumni', 'Alumni')], max_length=16)),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subgroup', to_field='slug')),
            ],
        ),
    ]
