# Generated by Django 3.0.7 on 2020-06-27 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200627_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subgroup', to_field='code'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subgroup', to_field='code'),
        ),
    ]
