# Generated by Django 3.0.7 on 2020-06-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200626_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('reg', 'publication'), ('spp', 'conference paper')], max_length=3),
        ),
    ]
