# Generated by Django 3.0.7 on 2020-06-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200626_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='award',
            name='awardee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='award',
            name='awarding_body',
            field=models.CharField(max_length=255),
        ),
    ]
