# Generated by Django 3.0.7 on 2020-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_project_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
