# Generated by Django 3.0.7 on 2020-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_subgroup_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='member',
            name='honorific',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('graduate', 'Graduate student'), ('undergraduate', 'Undergraduate student'), ('alumni', 'Alumni')], max_length=32),
        ),
        migrations.AlterField(
            model_name='member',
            name='suffix',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
