"""empty message

Revision ID: 1f1c26694c0a
Revises: 703226b2365c
Create Date: 2020-01-10 18:21:05.696110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1c26694c0a'
down_revision = '703226b2365c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'subgroup',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'subgroup',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###
