"""empty message

Revision ID: 20a1770f4e8c
Revises:
Create Date: 2020-01-08 02:26:22.729907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import func


# revision identifiers, used by Alembic.
revision = '20a1770f4e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('date_created', sa.DateTime(), nullable=False, server_default=func.now()),
    sa.Column('last_updated', sa.DateTime(), nullable=False, server_default=func.now()),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_type', sa.String(length=3), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('journal', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('issue', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    # ### end Alembic commands ###
