"""empty message

Revision ID: 6c2b2725e5e9
Revises: 161b9929dd83
Create Date: 2020-01-10 20:18:25.445780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2b2725e5e9'
down_revision = '161b9929dd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'url')
    # ### end Alembic commands ###
