"""empty message

Revision ID: d91e4ff54ade
Revises: 6c2b2725e5e9
Create Date: 2020-01-10 23:48:49.756152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91e4ff54ade'
down_revision = '6c2b2725e5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'doi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('doi', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
