# Generated by Django 2.2.5 on 2020-01-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('journal', models.CharField(max_length=512)),
                ('volume', models.CharField(max_length=32)),
                ('month', models.CharField(max_length=16)),
                ('year', models.IntegerField()),
                ('pubtype', models.CharField(max_length=3)),
            ],
        ),
    ]
